### ISSUE TITLE
Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException

### ISSUE THREAD

**Issue by emwtur** [ff4j/ff4j-spring-boot-starter-parent#245]
**Describe the bug**
Upgrading a working ff4j server from 
spring-boot-starter-parent version 2.3.3.Release to 2.6.3 will generate 
Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
on startup
It seems an underlying dependency to SpringFox has a bug and the recommendation is to replace it with Springdoc

**To Reproduce**
In 
ff4j-spring-boot-starter-parent\ff4j-spring-boot-sample
change 
 <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    _<version>2.5.3</version>_
  </parent>

to 
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    _<version>2.6.3</version>_
  </parent>

**Expected behavior**

**Screenshots**

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-01-31 11:54:03.838 ERROR 12636 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.15.jar:5.3.15]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_312]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) [spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414) [spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) [spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) [spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) [spring-boot-2.6.3.jar:2.6.3]
	at org.ff4j.sample.Application.main(Application.java:29) [classes/:na]

**Desktop (please complete the following information):**
 - OS: [Win10]

**Additional context**

**Comment by paul58914080** [comment]
Thanks for mentioning about this issue. 

I do like the proposal to use [springdoc-openapi-ui](https://springdoc.org/)

```
    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-ui</artifactId>
    </dependency>
```
